version: '3.1'

services:
  db:
    image: mysql:8
    cap_add:
      - SYS_NICE
    restart: always
    container_name: fastcamplus-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fast_sns
      MYSQL_USER: fast_user
      MYSQL_PASSWORD: password
      TZ: Asia/Seoul
    ports:
      - '3306:3306'
    expose:
      - '3306'
